// <auto-generated />
namespace TrashCollector.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedstateszipanddaysoftheweek : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedstateszipanddaysoftheweek));
        
        string IMigrationMetadata.Id
        {
            get { return "201703061352160_added states, zip, and days of the week"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
