// <auto-generated />
namespace TrashCollector.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedpuousercollectorandclienttable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedpuousercollectorandclienttable));
        
        string IMigrationMetadata.Id
        {
            get { return "201702281616191_added puo, user, collector, and client table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
